name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run Dev Experiment Job
      run: |
        az ml job create --file src/job.yml \
          --workspace-name aml-tccc-ms-training-dts-dsml-poc \
          --resource-group rg-tccc-ms-training-for-dts-dsml-poc \
          --set compute=Compute-Cluster \
          --set inputs.folder_name=diabetes-dev-folder \
          --set inputs.folder_version=1
          --stream

  train-prod:
    runs-on: ubuntu-latest
    environment: production  # This is your production environment with approvals
    needs: train-dev  # This ensures prod runs only after dev succeeds
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run Prod Experiment Job
      run: |
        az ml job create --file src/job.yml \
          --workspace-name aml-tccc-ms-training-dts-dsml-poc \
          --resource-group rg-tccc-ms-training-for-dts-dsml-poc \
          --set compute=Compute-Cluster \
          --set inputs.folder_name=diabetes-prod-folder \
          --set inputs